### ISSUE TITLE
DLL and XML file

### ISSUE THREAD

**Issue by stefanofattori** [Darkbat91/Powershell#3]
Where can I find xml and DLL file required by the script Get-PrinterCounts.ps1?

Thanks

**Comment by Darkbat91** [comment]
The XML file is based on the printers that you want to retrieve It is just the list of the Manufacturers and the IP Addresses. The SNMP library i unfortunately do not have in my notes which version i was using but a version is at the below link but your milage may vary, This repository is not maintained anymore. https://www.nuget.org/packages/Lextm.SharpSnmpLib/7.0.0.2
